stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        echo "Start download kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        kubectl get pods -n default
  - runScriptConfig:
      image: alpine
      shellScript: |-
        echo "Start download kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        kubectl get pods -n default
- name: backup
  steps:
  - runScriptConfig:
      image: bitnami/kubectl:latest
      shellScript: kubectl get pods
notification: {}
