stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        echo "Start download kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        pod=$(kubectl get pods -n default | tail -n+2 | awk '{print $1}')
        echo $pod
        sleep 300
notification: {}
