stages:
- name: Build
  steps:
  - runScriptConfig:
      image: bitnami/kubectl:latest
      shellScript: get pods
    envFrom:
    - sourceName: config
      sourceKey: config
      targetKey: KUBECONFIG
notification: {}
