stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |+
        echo "Start download kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        ls -latr
        DATE_TIME=$(date +%s)
        echo ### Do sed ###
        sed -i 's/NAME_SPACE/$NAME_SPACE/g' update-statefulset.sh
        sed -i 's/STS_NAME/$STS_NAME/g' update-statefulset.sh
        sed -i "s/REPLACE_ME_BY_DATETIME/$DATE_TIME/g" update-statefulset.sh
        echo ### finish do sed ###
        chmod +x *.sh
        #./update-statefulset.sh
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
        chmod +x jq
        mv jq /usr/local/bin/
        sleep 300














    env:
      NAME_SPACE: default
      STS_NAME: alpine-statefulset
notification: {}
