stages:
- name: Build
  steps:
  - runScriptConfig:
      image: bitnami/kubectl
      shellScript: kubectl get pods
    envFrom:
    - sourceName: config
      sourceKey: config
      targetKey: KUBECONFIG
notification: {}
