stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        env
        sleep 300
- name: backup
  steps:
  - runScriptConfig:
      image: bitnami/kubectl:latest
      shellScript: kubectl get pods
notification: {}
