stages:
- name: Build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        env
        pritnenv
        sleep 300
    envFrom:
    - sourceName: config
      sourceKey: config
      targetKey: KUBECONFIGFILE
- name: backup
  steps:
  - runScriptConfig:
      image: bitnami/kubectl:latest
      shellScript: kubectl get pods
notification: {}
