stages:
- name: Backup
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |+
        #####################################
        echo "Installing tools"
        wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        ln -s jq /usr/local/bin/jq
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/

        #####################################

        DATE_TIME=$(date +%s)
        echo ### Do sed ###
        sed -i "s/NAME_SPACE/$NAME_SPACE/g" update-statefulset.sh
        sed -i "s/STS_NAME/$STS_NAME/g" update-statefulset.sh
        sed -i "s/REPLACE_ME_BY_DATETIME/$DATE_TIME/g" update-statefulset.sh
        echo ### finish do sed ###
        chmod +x *.sh
        ./backup.sh
        #######################################















    env:
      NAME_SPACE: default
      STS_NAME: apache
- name: Config & Deploy
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |+
        #####################################
        echo "Installing tools"
        wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x jq
        mv jq /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/

        #####################################

        BASE_IMAGE_TAG=$(cat pipeline-properties.json | jq ."base_image")
        echo ### Do sed ###
        echo $NAME_SPACE
        echo $STS_NAME
        sed -i "s/NAME_SPACE/$NAME_SPACE/g" update-statefulset.sh
        sed -i "s/STS_NAME/$STS_NAME/g" update-statefulset.sh
        sed -i "s/REPLACE_ME_BY_BASE_IMAGE_ID/$BASE_IMAGE_TAG/g" update-statefulset.sh
        echo ### finish do sed ###
        chmod +x *.sh
        ./update-statefulset.sh
        sleep 1000
        #######################################















    env:
      NAME_SPACE: default
      STS_NAME: apache
notification: {}
