stages:
- name: Build
  steps:
  - runScriptConfig:
      image: bitnami/kubectl:latest
      shellScript: 
        - echo $KUBECONFIGFILE > kubeconfig.yaml
        - export KUBECONFIG='kubeconfig.yaml'
    envFrom:
    - sourceName: config
      sourceKey: config
      targetKey: KUBECONFIGFILE
notification: {}
